### ISSUE TITLE
Missing arrival times in gtfs-rt

### ISSUE THREAD

**Issue by cagryInside** [CUTR-at-USF/psta-data#13]
In trip (`trip_id=1208599020`), first two stop updates doesn't have arrival times.

According the Google gtfs-rt spec:

> The update can provide a exact timing for arrival and/or departure at a stop in StopTimeUpdates using StopTimeEvent. 

So, in my understanding PSTA doesn't have to send arrival and departure times together. One of them should be enough. However, OBA is only looking for arrival times and this is causing problems (OBA doesn't show the arrival times for first two bus stop).

cc'd @barbeau 

```
entity {
  id: "37"
  trip_update {
    trip {
      trip_id: "1208599020"
      route_id: "CAT"
    }
    stop_time_update {
      departure {
        time: 1436920798
      }
      stop_id: "4995"
    }
    stop_time_update {
      departure {
        time: 1436920798
      }
      stop_id: "5453"
    }
    stop_time_update {
      arrival {
        time: 1436920838
      }
      stop_id: "5040"
    }
    stop_time_update {
      arrival {
        time: 1436920860
      }
      stop_id: "5041"
    }
    stop_time_update {
      arrival {
        time: 1436920888
      }
      stop_id: "5042"
    }
    stop_time_update {
      arrival {
        time: 1436920931
      }
      stop_id: "5043"
    }
    stop_time_update {
      arrival {
        time: 1436920960
      }
      stop_id: "5044"
    }
    stop_time_update {
      arrival {
        time: 1436920988
      }
      stop_id: "5045"
    }
    stop_time_update {
      arrival {
        time: 1436921051
      }
      stop_id: "9863"
    }
    stop_time_update {
      arrival {
        time: 1436921051
      }
      stop_id: "5101"
    }
    stop_time_update {
      arrival {
        time: 1436921110
      }
      stop_id: "5046"
    }
    vehicle {
      id: "720"
    }
    timestamp: 1436919380
  }
}
```

**Comment by barbeau** [comment]
Correct, GTFS-rt feeds only have to supply an arrival or a departure, but
not both.  It's common to have only departures at the beginning of a trip
where a bus may be sitting at the first stop as part of a layover for a
while, waiting for the departure time before it leaves.  An arrival time in
this context doesn't really make sense.  Similarly, you might have only
arrival info for the last stop in the trip, since the bus doesn't "depart"
it as part of that trip if it is entering a layover period.

**Comment by cagryInside** [comment]
Ok then, we also need to handle this case. In `GtfsRealtimeTripLibrary` we only add time point predictions if there is an arrival time:
https://github.com/CUTR-at-USF/onebusaway-application-modules/blob/develop-psta2/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/realtime/gtfs_realtime/GtfsRealtimeTripLibrary.java#L367-L380

We can discuss this further, our tomorrow meeting.

**Comment by barbeau** [comment]
Interesting, I didn't think to check for that.  Yes, lets discuss tomorrow.

**Comment by barbeau** [comment]
@cagryInside I'm closing this, because it seems like the data is valid, its just OBA that needs to be adjusted to handle this case.

**Comment by barbeau** [comment]
This issue was moved to General-Transit-Feed-Specification/psta-fl-us#13
