### ISSUE TITLE
Bad shape data for "11 – South St. Pete/ PSTA 34th ST"

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/psta-data#15]
Something is wrong with the shapes.txt data for "11 – South St. Pete/ PSTA 34th ST" – this is what it looks like in OBA (from http://app.staging.obahart.org/where/standard/#m(route)route(PSTA_11)):

![image](https://cloud.githubusercontent.com/assets/928045/10643378/7eb1d122-77f0-11e5-8350-6d64d59f7460.png)

Because OBA uses shape data to interpolate vehicle positions when no real-time info is available, this also results in some interesting vehicle travel patterns :).

![image](https://cloud.githubusercontent.com/assets/928045/10643677/12bd929c-77f2-11e5-8296-32e625db467f.png)

We should check this again after they notify us with the new GTFS data.

**Comment by barbeau** [comment]
This still exists in PSTA_S0000213.zip.

**Comment by cagryInside** [comment]
Seems fixed via PSTA_S0000220

![device-2015-12-18-095947](https://cloud.githubusercontent.com/assets/2777974/11899614/37ac32a8-a56e-11e5-93cd-0c96b8156931.png)

**Comment by barbeau** [comment]
Agreed, I just looked as well!

**Comment by barbeau** [comment]
This issue was moved to General-Transit-Feed-Specification/psta-fl-us#11
