### ISSUE TITLE
GTFS-rt - More than one Trip Update record for the same vehicle

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/psta-data#9]
Looks like we're currently dropping all but one trip update for the same vehicle, even if the trips are in the same block:

```
2015-03-23 18:34:15,940 INFO  [GtfsRealtimeSource.java:232] : refreshing http://97.76.252.61:8080/gtfsrt/trips
2015-03-23 18:34:16,463 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2903; taking newest.
2015-03-23 18:34:16,463 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 821; taking newest.
2015-03-23 18:34:16,463 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2531; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2718; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2715; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2308; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2717; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2711; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2611; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2114; taking newest.
2015-03-23 18:34:16,464 WARN  [GtfsRealtimeTripLibrary.java:139] : 
Multiple TripUpdates for vehicle 2716; taking newest.
```

**Comment by barbeau** [comment]
We’re looking at how GTFS-rt and OneBusAway handles more than one trip per vehicle to make sure it’s being handled correctly.

**Comment by barbeau** [comment]
From @cagryInside:

> I look at the code and try to understand how we handle trip updates.
> We store the trip updates in the map. And as a key, we use vehicle id:
> 
> ```
> Map<String, TripUpdate> tripUpdatesByVehicleId = new HashMap<String, 
> TripUpdate>(); if (!tripUpdatesByVehicleId.containsKey(vehicleId)) {
>            tripUpdatesByVehicleId.put(vehicleId, tu);
>          } else {
>            _log.warn("Multiple TripUpdates for vehicle {}; taking newest.",
>                vehicleId);
>            TripUpdate otherUpdate = tripUpdatesByVehicleId.get(vehicleId);
>          .....
> ```
> 
> So, We override the trip updates without looking their trip IDs. I think we should store also trip IDs too.

me:

> I recall Kurt saying we store everything in terms of blocks at some level.  Is there any link between a particular stop_time_update and a block (which could contain multiple trips)?

@cagryInside:

> Yes, there is a link.
> 
> After preparing the tripUpdate map with vehicle id, we combine trip updates and vehicle positions:
> 
> ```
> // Map updates by vehicle ID
>      for (Map.Entry<String, TripUpdate> e : tripUpdatesByVehicleId.entrySet()) {
>        CombinedTripUpdatesAndVehiclePosition update = new 
> CombinedTripUpdatesAndVehiclePosition();
> 
>        String vehicleId = e.getKey();
>        TripUpdate tu = e.getValue();
>        update.block = getTripDescriptorAsBlockDescriptor(result, tu.getTrip());
>        update.tripUpdates = Collections.singletonList(tu);
> 
>        if (vehiclePositionsByVehicleId.containsKey(vehicleId)) {
>          update.vehiclePosition = vehiclePositionsByVehicleId.get(vehicleId);
>        }
> 
>        updates.add(update);
>      }
> 
> ```
> 
> So, if we skip some trips before, while preparing "tripUpdatesByVehicleId" map, in here we might not update the "CombinedTripUpdatesAndVehiclePosition " correctly.

Me:

> Could you also please confirm that the trip_ids that are showing up for the same PSTA vehicle have the same block_id in the GTFS data?  I’d like to make sure that it’s valid real-time/schedule data, and the same bus could actually travel from one of these trips to another.

@cagryInside:

> I looked for couple PSTA data, and they have the same block ids:
> 
> For vehicle id: "2717"
> Block # PSTA_16073902
> Block # PSTA_16073902
> 
> For vehicle id: "10101"
> Block # PSTA_16078802
> Block # PSTA_16078802

**Comment by barbeau** [comment]
@cagryInside could you please provide links to main OBA Github repo to the code sections you mentioned above?  Thanks!

**Comment by cagryInside** [comment]
@barbeau Currently, we are using the OBA application from camsys repository develop-freq branch (https://github.com/camsys/onebusaway-application-modules/tree/develop-freq).

Trip updates handled in here:
- https://github.com/camsys/onebusaway-application-modules/blob/develop-freq/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/realtime/gtfs_realtime/GtfsRealtimeTripLibrary.java#L132-L144

``` java
if (tu.hasVehicle() && tu.getVehicle().hasId()) {
// Trip update has a vehicle ID - index by vehicle ID
String vehicleId = tu.getVehicle().getId();
if (!tripUpdatesByVehicleId.containsKey(vehicleId)) {
tripUpdatesByVehicleId.put(vehicleId, tu);
} else {
_log.warn("Multiple TripUpdates for vehicle {}; taking newest.",
vehicleId);
TripUpdate otherUpdate = tripUpdatesByVehicleId.get(vehicleId);
long otherTimestamp = otherUpdate.getTimestamp();
```
- https://github.com/camsys/onebusaway-application-modules/blob/develop-freq/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/realtime/gtfs_realtime/GtfsRealtimeTripLibrary.java#L243-L255

``` java
 for (Map.Entry<String, TripUpdate> e : tripUpdatesByVehicleId.entrySet()) {
  CombinedTripUpdatesAndVehiclePosition update = new CombinedTripUpdatesAndVehiclePosition();
  String vehicleId = e.getKey();
  TripUpdate tu = e.getValue();
  update.block = getTripDescriptorAsBlockDescriptor(result, tu.getTrip());
  update.tripUpdates = Collections.singletonList(tu);
  if (vehiclePositionsByVehicleId.containsKey(vehicleId)) {
    update.vehiclePosition = vehiclePositionsByVehicleId.get(vehicleId);
  }
updates.add(update);
```

However, in the OneBusAway repository master branch, Trip updates flow is different:
https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/realtime/gtfs_realtime/GtfsRealtimeTripLibrary.java#L97-L126

IMO, there should be some problem with current develop-freq branch. I will test with the OBA master branch.

**Comment by cagryInside** [comment]
@barbeau I just introduced an alternative solution to this problem.
Basically, I concatenate the vehicle id and trip id. Like that, we don't override the trips which has the same vehicle ids.

``` java
    String vehicleId = tu.getVehicle().getId() + "_" + tu.getTrip().getTripId();

            if (!tripUpdatesByVehicleId.containsKey(vehicleId)) {
              tripUpdatesByVehicleId.put(vehicleId, tu);
            } else {
              _log.warn("Multiple TripUpdates for vehicle and trip {}; taking newest.",
                  vehicleId);
```

For example, after this implementation, we don't get any " Multiple TripUpdates for vehicle" warning for PSTA.

For bullrunner real-time feed, we get the following error:
This is an expected behavior for bullrunner (since it has duplicate trip updates).

```
2015-03-26 13:57:23,892 INFO  [GtfsRealtimeSource.java:232] : refreshing http://mobullity.forest.usf.edu:8088/trip-updates
2015-03-26 13:57:23,907 WARN  [GtfsRealtimeTripLibrary.java:139] : Multiple TripUpdates for vehicle 9012_3; taking newest.
2015-03-26 13:57:23,907 WARN  [GtfsRealtimeTripLibrary.java:139] : Multiple TripUpdates for vehicle 1326_5; taking newest.
2015-03-26 13:57:23,907 WARN  [GtfsRealtimeTripLibrary.java:139] : Multiple TripUpdates for vehicle 2102_1; taking newest.
2015-03-26 13:57:23,907 WARN  [GtfsRealtimeTripLibrary.java:139] : Multiple TripUpdates for vehicle 2236_3; taking newest.
2015-03-26 13:57:23,907 WARN  [GtfsRealtimeTripLibrary.java:139] : Multiple TripUpdates for vehicle 1124_8; taking newest.

```

**Comment by barbeau** [comment]
@cagryInside Thanks for looking into this.  So the issue with map collisions for multiple GTFS-rt trip_ids for the same vehicle (that we're seeing using the camsys develop-freq branch) exists in the current OBA master branch too?

The FOR loop through the `tripUpdatesByBlockDescriptor` map in the master branch seems more reasonable to me, since its iterating through the entire block.  Let's talk more about this tomorrow.

**Comment by barbeau** [comment]
Since this seems to be an issue with OBA and not the GTFS-rt data, I'm going to close this issue.  We've opened another issue at https://github.com/OneBusAway/onebusaway-application-modules/issues/128 to track this.
